/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this file,
 * You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

interface nsIDOMMozVoicemailStatus;

%{C++
#define VOICEMAIL_SERVICE_CID { 0x091589e8, 0x7551, 0x48ee, { 0xb9, 0xc2, 0xe2, 0x3e, 0x0b, 0x51, 0xe8, 0x4c } }
#define VOICEMAIL_SERVICE_CONTRACTID "@mozilla.org/voicemail/service;1"
%} 

[scriptable, uuid(afd22f7b-9980-4fbc-bd51-cbd8888fec22)]
interface nsIVoicemailListener : nsISupports
{
  /**
   * Called when a voicemail notification has been received by the network.
   *
   * @param status
   *        The new voicemail status
   */
  void notifyStatusChanged(in nsIDOMMozVoicemailStatus status);
};

/**
 * XPCOM component (in the content process) that provides the voicemail
 * information.
 */
[scriptable, uuid(22d41e2a-dab2-40f6-ac0c-33cd0f15e1e1)]
interface nsIVoicemailProvider : nsISupports
{
  /**
   * Called when a content process registers receiving unsolicited messages from
   * RadioInterfaceLayer in the chrome process. Only a content process that has
   * the 'voicemail' permission is allowed to register.
   */
  void register(in nsIVoicemailListener listener);
  void unregister(in nsIVoicemailListener listener);
  readonly attribute DOMString number;
  readonly attribute DOMString displayName;
};
